services:
  app:
    image: node-app
    build:
      context: .
    environment:
      DBHOST: db
    ports:
      - "8080:8080"
    volumes:
      - db_volume:/app/logs
    depends_on:
      - db
  db:
    image: mongo

volumes:
  db_volume:
